##########################
## profile:dev
##########################
management:
  security:
    enabled: false
server:
  port: 9993


spring:
  boot:
    swagger2:
      enable: true
      title: 邮件开放平台
      description: 邮件开放平台
      version: 1.1.1
      contactName: BBB
      contactEmail: vastpn@info.com
      contactUrl: http://www.vastpn.com

